version: "3.9"
services:
  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
  app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - "./:/app"
volumes:
  redis:
