version: "3.9"
services:
  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    restart: on-failure
  app:
    build: ./
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - "./:/app"
    restart: on-failure
volumes:
  redis:
