name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout project
        uses: actions/checkout@v2
        with:
          clean: false
      - name: install dependencies
        run: |
          docker-compose restart app